### ISSUE TITLE
What is the project for? Any help needed?

### ISSUE THREAD

**Issue by YanDatsiuk** [mCassy/repotracker#1]
Hi!
Could you specify purposes of the project, or create any tasks in "todo" list?

**Comment by mCassy** [comment]
Hi there! 
The main idea of this project is to help developers to track movements of the git branch/Jira issue in repository or environments. Currently, we are trying to define the minimum required a set of features. Will get back with updates soon.
If it is interesting for you it would be really good to collaborate :)
